### ISSUE TITLE
プログラムと登壇者の詳細に関連リンクを追加する

### ISSUE THREAD

**Issue by shamrock1976** [code4nerima/summitman#3]
プログラムと登壇者の詳細に関連リンクを追加する。とりあえず３つくらい設定できるように。

**Comment by jinka1997** [comment]
APIは↓で対応。
- CreateProgram/UpdateProgram
- CreatePresenter/UpdatePresenter

**Comment by shamrock1976** [comment]
実装完了。とりあえず１つだけ。
